---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    type: db
    author: bharath 
spec:
  containers:
    - name: mypg
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: bharath
        - name: POSTGRES_USER
          value: myuser
        - name: POSTGRES_DB
          value: mydb
...
